name: cicd

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v2 

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with: 
          node-versoin: 16

      - name: Download dependencies
        run: npm install

      - name: Run tests
        run: npm rum test
        
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with: 
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
  
